### ISSUE TITLE
是否能提供一个jar

### ISSUE THREAD

**Issue by Chenshuai770** [xkzhangsan/xk-time#28]
是否能提供一个jar,前后端都可以使用

**Comment by xkzhangsan** [comment]
Maven坐标:

<dependency>  
  <groupId>com.github.xkzhangsan</groupId>    
  <artifactId>xk-time</artifactId>       
  <version>2.1.0</version>    
</dependency>

**Comment by xkzhangsan** [comment]
> 是否能提供一个jar,前后端都可以使用

这个项目是提供jar的:
<dependency>  
  <groupId>com.github.xkzhangsan</groupId>    
  <artifactId>xk-time</artifactId>       
  <version>2.1.0</version>    
</dependency>

**Comment by Chenshuai770** [comment]
我在android端使用的时候,调用String ancientTime = DateTimeCalculatorUtil.getTwelveTwo();出现异常 java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalTime;我项目里面有使用jodaTime,是否会导致冲突

**Comment by xkzhangsan** [comment]
> 我在android端使用的时候,调用String ancientTime = DateTimeCalculatorUtil.getTwelveTwo();出现异常 java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalTime;我项目里面有使用jodaTime,是否会导致冲突

和joda-time没有关系，包路径不同，先要确认jdk版本是否为8或8以上。
