### ISSUE TITLE
在android端通过会出现问题

### ISSUE THREAD

**Issue by Chenshuai770** [xkzhangsan/xk-time#29]
LocalDate localDate = DateTimeConverterUtil.toLocalDate(TimeUtils.getNowMills());
 java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;

**Comment by xkzhangsan** [comment]
> LocalDate localDate = DateTimeConverterUtil.toLocalDate(TimeUtils.getNowMills());
> java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;

你使用的jdk版本是多少? Android SDK版本是多少?

Instant 是Java8的新增类，Android 端没有试过。

**Comment by Chenshuai770** [comment]
使用的jdk是Java8，Android Sdk是26

**Comment by xkzhangsan** [comment]
> 使用的jdk是Java8，Android Sdk是26

好，我先看看

**Comment by Chenshuai770** [comment]
我在github写了一个测试项目，已经引入了xk_time，写好了测试类，大神可以编译项目直接看看，android studo版本为3.6.3
https://github.com/Chenshuai770/test_xk_time

**Comment by xkzhangsan** [comment]
好

**Comment by xkzhangsan** [comment]
> 使用的jdk是Java8，Android Sdk是26

已经验证过，Java8，SDK26 Android studio 3.5.2.
没有问题。

**Comment by xkzhangsan** [comment]
> 我在github写了一个测试项目，已经引入了xk_time，写好了测试类，大神可以编译项目直接看看，android studo版本为3.6.3
> https://github.com/Chenshuai770/test_xk_time

问题可能在于 配置 
minSdkVersion 19

> 我在github写了一个测试项目，已经引入了xk_time，写好了测试类，大神可以编译项目直接看看，android studo版本为3.6.3
> https://github.com/Chenshuai770/test_xk_time

看了配置项，应该是 minSdkVersion 19 问题，需要兼容低版本，同时你使用的模拟器版本太低（我使用Oreo模拟器是没有问题的），不支持Java8导致的。

https://stackoverflow.com/questions/49851379/java-lang-noclassdeffounderror-failed-resolution-of-ljava-time-instant

由于本项目只支持Java8及以上版本。Android端要兼容低版本需求，谨慎使用，建议继续使用joda-time，如果有需要实现的功能，可以参考本项目源码，也可以留言给我。
感谢支持！

**Comment by Chenshuai770** [comment]
我使用的是真机测试,目前考虑兼容性不能将minsdkVersion改为26,但是我用joda-time提供了android版本,不需要考虑minSdk的问题,https://github.com/dlew/joda-time-android,xk_time是否能考虑做一个更强大的适配版本,可取代joda_time

**Comment by xkzhangsan** [comment]
> 我使用的是真机测试,目前考虑兼容性不能将minsdkVersion改为26,但是我用joda-time提供了android版本,不需要考虑minSdk的问题,https://github.com/dlew/joda-time-android
> xk_time是否能考虑做一个更强大的适配版本,可取代joda_time

xk-time做适配Java8以下版本可能性比较小，原因是xk-time是基于Java8实现的，是Java8新日期时间API的扩展应用。

joda-time是Java8新日期时间API的前身，都是同一个人开发的。
joda-time不同版本都可以兼容使用，Java8新日期时间API只能使用与Java8及以上版本。
所以，本项目也只能使用Java8及以上版本，无法取代joda-time。

Android端因为需要兼容低版本，建议继续使用joda-time，如果有需要本项目相关的功能，可以参考源码实现，或留言给我。
感谢支持！
