### ISSUE TITLE
支持自然语言解析吗？？

### ISSUE THREAD

**Issue by aircjm** [xkzhangsan/xk-time#37]
例如： "明天" "下周" 这样的文本 转化成对应的时间

**Comment by xkzhangsan** [comment]
> 例如： "明天" "下周" 这样的文本 转化成对应的时间

目前不支持。"明天"指的是下一天0点0分吗；"下周"指的是下周一的0点0分吗？

**Comment by xkzhangsan** [comment]
> > 例如： "明天" "下周" 这样的文本 转化成对应的时间
> 
> 目前不支持。"明天"指的是下一天0点0分吗；"下周"指的是下周一的0点0分吗？

如果是这样的话，后面增加支持。

**Comment by aircjm** [comment]
明天10点 指的是明天的10点 明天指的是下一天的当前时间 也就是day+1
下周 明年 下周日这样的

**Comment by xkzhangsan** [comment]
> 明天10点 指的是明天的10点 明天指的是下一天的当前时间 也就是day+1
> 下周 明年 下周日这样的

按照这样实现了，支持解析自然语言时间，今天，明天，下周，下月，明年，昨天，上周，上月，去年等，支持自定义解析自然语言时间。

**Comment by aircjm** [comment]
强 我试试

**Comment by tomxin7** [comment]
如果自然语言还可以加强一下就更完美了，作者可以参考 https://github.com/shinyke/Time-NLP

**Comment by xkzhangsan** [comment]
> 如果自然语言还可以加强一下就更完美了，作者可以参考 https://github.com/shinyke/Time-NLP

看了一下，这个项目很好，能够做到识别夹杂在语句中的时间，并且能够结合上下文解析，看到issue中的描述，有一点识别失败概率。
我尝试做一下，需要耗费一些时间。

**Comment by xkzhangsan** [comment]
> 如果自然语言还可以加强一下就更完美了，作者可以参考 https://github.com/shinyke/Time-NLP

有一个问题，这个项目核心的是使用TimeExp.m正则匹配，如果有范围时间，出现2个时间，会有问题，比如:下周三到周五第二个时间识别出为本周五。
这种有没有好的解决方案？

**Comment by xkzhangsan** [comment]
> 如果自然语言还可以加强一下就更完美了，作者可以参考 https://github.com/shinyke/Time-NLP

已加入此功能，并做了大量修改，欢迎提建议。
