### ISSUE TITLE
NLP解析时间功能请求修复

### ISSUE THREAD

**Issue by huiyang-work** [xkzhangsan/xk-time#46]
非常感谢，用到NLP功能发现这里提交的很多issues（https://github.com/shinyke/Time-NLP/issues）在项目中仍存在，原项目长时间未维护，望大神修复。

**Comment by xkzhangsan** [comment]
> 非常感谢，用到NLP功能发现这里提交的很多issues（[https://github.com/shinyke/Time-NLP/issues）在项目中仍存在，原项目长时间未维护，望大神修复。](https://github.com/shinyke/Time-NLP/issues%EF%BC%89%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BB%8D%E5%AD%98%E5%9C%A8%EF%BC%8C%E5%8E%9F%E9%A1%B9%E7%9B%AE%E9%95%BF%E6%97%B6%E9%97%B4%E6%9C%AA%E7%BB%B4%E6%8A%A4%EF%BC%8C%E6%9C%9B%E5%A4%A7%E7%A5%9E%E4%BF%AE%E5%A4%8D%E3%80%82)

我会抽时间尽力修复这些问题，也希望大家能参与进来。

**Comment by xkzhangsan** [comment]
已修复issue：
1.标准时间yyyy-MM-dd、yyyy-MM-dd HH:mm:ss和yyyy-MM-dd HH:mm解析问题。   
2.1小时后，1个半小时后，1小时50分钟等解析问题；并且支持到秒，比如50秒后，10分钟30秒后等。

**Comment by xkzhangsan** [comment]
已修复issue：
3.当前时间是上午10点，那么下午三点 会识别为明天下午三点问题。

**Comment by xkzhangsan** [comment]
> 非常感谢，用到NLP功能发现这里提交的很多issues（[https://github.com/shinyke/Time-NLP/issues）在项目中仍存在，原项目长时间未维护，望大神修复。](https://github.com/shinyke/Time-NLP/issues%EF%BC%89%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BB%8D%E5%AD%98%E5%9C%A8%EF%BC%8C%E5%8E%9F%E9%A1%B9%E7%9B%AE%E9%95%BF%E6%97%B6%E9%97%B4%E6%9C%AA%E7%BB%B4%E6%8A%A4%EF%BC%8C%E6%9C%9B%E5%A4%A7%E7%A5%9E%E4%BF%AE%E5%A4%8D%E3%80%82)

已修复issue：
4.当前时间是小数解析成时间问题。

原项目中的主要问题都已修复完成，至于其他一些需求比如节假日的支持后续会增加。

**Comment by xkzhangsan** [comment]
> 非常感谢，用到NLP功能发现这里提交的很多issues（[https://github.com/shinyke/Time-NLP/issues）在项目中仍存在，原项目长时间未维护，望大神修复。](https://github.com/shinyke/Time-NLP/issues%EF%BC%89%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BB%8D%E5%AD%98%E5%9C%A8%EF%BC%8C%E5%8E%9F%E9%A1%B9%E7%9B%AE%E9%95%BF%E6%97%B6%E9%97%B4%E6%9C%AA%E7%BB%B4%E6%8A%A4%EF%BC%8C%E6%9C%9B%E5%A4%A7%E7%A5%9E%E4%BF%AE%E5%A4%8D%E3%80%82)

已修复issue：
4.小数解析成时间问题。

原项目中的主要问题都已修复完成，至于其他一些需求比如节假日的支持后续会增加。

**Comment by xkzhangsan** [comment]
在即将发布的3.0.0版本中修复上面的问题。
