### ISSUE TITLE
获取中国工作日（去除每年发布的调休日）得问题

### ISSUE THREAD

**Issue by 799983050** [xkzhangsan/xk-time#54]
1、感谢作者开发这么强大的工具类，是否有个交流群啊，大家一起交流交流
2、现在有个需求是获取中国工作日的问题。现在是看到CalendarUtil可以自定义节假日和工作日，可否在这个基础上继续扩展，获取工作日的方法 和 判断当天是否是工作日、获取下一个工作日
@xkzhangsan

**Comment by xkzhangsan** [comment]
> 1、感谢作者开发这么强大的工具类，是否有个交流群啊，大家一起交流交流
> 2、现在有个需求是获取中国工作日的问题。现在是看到CalendarUtil可以自定义节假日和工作日，可否在这个基础上继续扩展，获取工作日的方法 和 判断当天是否是工作日、获取下一个工作日
> @xkzhangsan

发现这个需求不少人需要，最近会实现这个功能，感谢提建议！

**Comment by xkzhangsan** [comment]
计划从2021年开始，数据从官方放假通知文件中获取，每年更新数据。

**Comment by xkzhangsan** [comment]
在即将发布的3.0.0版本中添加此功能。

**Comment by xkzhangsan** [comment]
3.0版本工作日功能有问题，会发一个版本修复这个问题。

**Comment by xkzhangsan** [comment]
已修复问题：
传参holidayData 放假信息0表示放假，1表示工作日，如：2021-01-01:0,2021-02-07:1。

2021年放假信息：
		String holidayData = "2021-01-01:0,2021-02-07:1,2021-02-11:0,2021-02-12:0,2021-02-15:0,2021-02-16:0,2021-02-17:0,2021-02-20:1,2021-04-05:0,2021-04-25:1,2021-05-03:0,2021-05-04:0,2021-05-05:0,2021-05-08:1,2021-06-14:0,2021-09-18:1,2021-09-20:0,2021-09-21:0,2021-09-26:1,2021-10-01:0,2021-10-04:0,2021-10-05:0,2021-10-06:0,2021-10-07:0,2021-10-09:1";

**Comment by xkzhangsan** [comment]
3.0.1已修复问题：
传参holidayData 放假信息0表示放假，1表示工作日，如：2021-01-01:0,2021-02-07:1。

2021年放假信息：
String holidayData = "2021-01-01:0,2021-02-07:1,2021-02-11:0,2021-02-12:0,2021-02-15:0,2021-02-16:0,2021-02-17:0,2021-02-20:1,2021-04-05:0,2021-04-25:1,2021-05-03:0,2021-05-04:0,2021-05-05:0,2021-05-08:1,2021-06-14:0,2021-09-18:1,2021-09-20:0,2021-09-21:0,2021-09-26:1,2021-10-01:0,2021-10-04:0,2021-10-05:0,2021-10-06:0,2021-10-07:0,2021-10-09:1";
