### ISSUE TITLE
2021-08-31 09:27:00，NLP parsing error

### ISSUE THREAD

**Issue by bestRunner** [xkzhangsan/xk-time#93]
The current date is August 30，TimeNLPUtil.parse("昨天09:27")，program output:2021-08-31 09:27:00，正确时间应该是”2021-08-29 09:27:00“

**Comment by xkzhangsan** [comment]
不好意思，我今天晚点查一下原因，感谢支持！

**Comment by bestRunner** [comment]
> 不好意思，我今天晚点查一下原因，感谢支持！

感谢您的回复，"前天17:00"，也会输出"2021-09-02 17:00:00"，好像对于“昨天”，“前天”这类词，时间出现反向计算了

**Comment by xkzhangsan** [comment]
> > 不好意思，我今天晚点查一下原因，感谢支持！
> 
> 感谢您的回复，"前天17:00"，也会输出"2021-09-02 17:00:00"，好像对于“昨天”，“前天”这类词，时间出现反向计算了

感谢参与项目，这个问题将在3.2.2版本中修复。
