### ISSUE TITLE
时间解析：组合时间有些细节问题，如“1小时50分钟后”只追加了50分钟，1小时给忽略了

### ISSUE THREAD

**Issue by mbb2100** [xkzhangsan/xk-time#99]
您好，测试了一下您源码中的测试用例，发现了如下bug
**1个半小时后对应时间**是能正常解析出对的时间
**1小时50分钟后对应时间**就只追加了50分钟，前面的一小时就给忽略掉了；

同理，后面**10分钟后对应时间**和**10分钟30秒后对应时间**存在同样的问题

同时测试了一下**时分秒**三个的组合，也有同样的问题

![](https://user-images.githubusercontent.com/4435654/146860211-f4a4a3a1-3052-4982-90a3-3ed88ec95691.png)

**Comment by mbb2100** [comment]
测试时间为10点20分

**Comment by mbb2100** [comment]
辛苦了，这么晚了还在修复bug，收到您的修复邮件之后，第一时间更新做了一下测试；
1小时50分钟的这个问题是解决了，但是还存在另一个细节问题就是：**1小时50分钟10秒**后这个文本，前面的1小时也被忽略了，您方便的时候，一起修复一下

您看一下下图的测试用例
**1小时50分钟10秒**和**50分钟10秒**输出的结果是一样的
![image](https://user-images.githubusercontent.com/4435654/147124117-f388c040-0500-43f6-93a5-27d6420d51b0.png)

**Comment by mbb2100** [comment]
您好：
&nbsp; &nbsp; &nbsp;辛苦了，这么晚了还在修复bug，收到您的修复邮件之后，第一时间更新做了一下测试；

1小时50分钟的这个问题是解决了，但是还存在另一个细节问题就是：1小时50分钟10秒后这个文本，前面的1小时也被忽略了，您方便的时候，一起修复一下

您看一下下图的测试用例
1小时50分钟10秒和50分钟10秒输出的结果是一样的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xkzhangsan/xk-time"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 晚上11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xkzhangsan/xk-time] 时间解析：组合时间有些细节问题，如“1小时50分钟后”只追加了50分钟，1小时给忽略了 (Issue #99)





 
Closed #99.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xkzhangsan** [comment]
> 

多种情况组合叠加在一起的情况会出现问题，已修复这个问题，感谢支持！

**Comment by xkzhangsan** [comment]
> 您好： &nbsp; &nbsp; &nbsp;辛苦了，这么晚了还在修复bug，收到您的修复邮件之后，第一时间更新做了一下测试； 1小时50分钟的这个问题是解决了，但是还存在另一个细节问题就是：1小时50分钟10秒后这个文本，前面的1小时也被忽略了，您方便的时候，一起修复一下 您看一下下图的测试用例 1小时50分钟10秒和50分钟10秒输出的结果是一样的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xkzhangsan/xk-time" ***@***.***&gt;; 发送时间:&nbsp;2021年12月22日(星期三) 晚上11:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xkzhangsan/xk-time] 时间解析：组合时间有些细节问题，如“1小时50分钟后”只追加了50分钟，1小时给忽略了 (Issue #99) Closed #99. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

多种情况组合叠加在一起的情况会出现问题，已修复这个问题，感谢支持！

**Comment by mbb2100** [comment]
感谢您的修复！
请问您，修复的这俩问题，近期有计划更新maven仓库版本吗？

**Comment by xkzhangsan** [comment]
> 感谢您的修复！ 请问您，修复的这俩问题，近期有计划更新maven仓库版本吗？

这个周末会发一个版本。

**Comment by xkzhangsan** [comment]
> > 感谢您的修复！ 请问您，修复的这俩问题，近期有计划更新maven仓库版本吗？
> 
> 这个周末会发一个版本。

已经发布到maven仓库，感谢支持！

**Comment by xkzhangsan** [comment]
> 感谢您的修复！ 请问您，修复的这俩问题，近期有计划更新maven仓库版本吗？

已经发布到maven仓库，感谢支持！

**Comment by mbb2100** [comment]
您好，发现了一个新的问题

当前时间：1月7号 16点03分
执行“16点50分”时，会被解析到明天的下午16点50分
![image](https://user-images.githubusercontent.com/4435654/148512303-37f40599-ac32-46dc-adfd-8d446efe3e66.png)

但是执行下一个小时的时间，如“17点01分”时，就能正确解析
![image](https://user-images.githubusercontent.com/4435654/148512463-ff99e7b0-77ad-4dc7-8a1e-da5ce9c56486.png)

**Comment by mbb2100** [comment]
另外的问题；
如解析“5秒后10分钟后”，时间不对，那怕是以“5秒后”、“10分钟后”任意一个时间解析也成，但是解析出来返回的是一个错误的时间，示例如下
![image](https://user-images.githubusercontent.com/4435654/148541824-7a64e22b-2ffd-4d87-9838-d05bad6b13cc.png)

**Comment by xkzhangsan** [comment]
> 您好，发现了一个新的问题
> 
> 当前时间：1月7号 16点03分 执行“16点50分”时，会被解析到明天的下午16点50分 ![image](https://user-images.githubusercontent.com/4435654/148512303-37f40599-ac32-46dc-adfd-8d446efe3e66.png)
> 
> 但是执行下一个小时的时间，如“17点01分”时，就能正确解析 ![image](https://user-images.githubusercontent.com/4435654/148512463-ff99e7b0-77ad-4dc7-8a1e-da5ce9c56486.png)

这个是对时间是否是未来时间判断出现问题，下次发布修复这个问题。

**Comment by xkzhangsan** [comment]
> 另外的问题； 如解析“5秒后10分钟后”，时间不对，那怕是以“5秒后”、“10分钟后”任意一个时间解析也成，但是解析出来返回的是一个错误的时间，示例如下 ![image](https://user-images.githubusercontent.com/4435654/148541824-7a64e22b-2ffd-4d87-9838-d05bad6b13cc.png)

对于这种“5秒后10分钟后” 复杂的组合暂时不支持，你如果感兴趣可以参考源码，想一下实现方案，我们一起讨论如何实现比较好。
